### ISSUE TITLE
DaylightPortalNode

### ISSUE THREAD

**Issue by awesome-coder** [jeremytammik/TwglExport#1]
lack DaylightPortalNode ,how to solte

**Comment by jeremytammik** [comment]
1. run your description through a spell checker before submitting an issue.
2. `DaylightPortalNode` did not exist in the Revit 2015 API. It was introduced in Revit 2017. In Revit 2018 obsolete and no longer exists, cf. the Revit API docs at http://www.revitapidocs.com/2017/85a6e9b3-6cb9-0e15-9c5d-40e9d240fd49.htm
